source "https://rubygems.org"

gem "anthropic", "~> 0.4"
gem "colorize", "~> 1.1"
gem "ruby-openai", "~> 7.3"
gem "googleauth", "~> 1.11"
gem "thor", "~> 1.3"

group :test do
  gem "minitest", "~> 5.25"
  gem "rake", "~> 13.2"
end
